# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_order.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user_order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10user_order.proto\x12\x03\x61pp\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"*\n\x0fGetUserResponse\x12\x17\n\x04user\x18\x01 \x01(\x0b\x32\t.app.User\"$\n\x11ListOrdersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"0\n\x12ListOrdersResponse\x12\x1a\n\x06orders\x18\x01 \x03(\x0b\x32\n.app.Order\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"A\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04item\x18\x03 \x01(\t\x12\r\n\x05total\x18\x04 \x01(\x01\x32\x45\n\x0bUserService\x12\x36\n\x07GetUser\x12\x13.app.GetUserRequest\x1a\x14.app.GetUserResponse\"\x00\x32O\n\x0cOrderService\x12?\n\nListOrders\x12\x16.app.ListOrdersRequest\x1a\x17.app.ListOrdersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=25
  _globals['_GETUSERREQUEST']._serialized_end=58
  _globals['_GETUSERRESPONSE']._serialized_start=60
  _globals['_GETUSERRESPONSE']._serialized_end=102
  _globals['_LISTORDERSREQUEST']._serialized_start=104
  _globals['_LISTORDERSREQUEST']._serialized_end=140
  _globals['_LISTORDERSRESPONSE']._serialized_start=142
  _globals['_LISTORDERSRESPONSE']._serialized_end=190
  _globals['_USER']._serialized_start=192
  _globals['_USER']._serialized_end=239
  _globals['_ORDER']._serialized_start=241
  _globals['_ORDER']._serialized_end=306
  _globals['_USERSERVICE']._serialized_start=308
  _globals['_USERSERVICE']._serialized_end=377
  _globals['_ORDERSERVICE']._serialized_start=379
  _globals['_ORDERSERVICE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
